### ISSUE TITLE
aeon-wallet-cli: seg fault

### ISSUE THREAD

**Issue by camthegeek** [aeonix/aeon#101]
When using a ringsize **greater** than 161, aeon-wallet-cli will throw a segmentation fault. Ringsizes 161 or less will work as seen here: http://testnet.aeon.lol/tx/feee200b8b4434ab40794fbd9b8d308c47d5e5afbd1a7bd3044acdc559f20944

I was able to reproduce the error from _release_ versions 12.6, 12.8 and current master at 01e5cde.

The following logs provided are using current master at head 01e5cde built using debug instead of release and ran in gdb per [debugging instructions](https://github.com/aeonix/aeon#debugging)

```
[wallet Umj5Dh]: transfer 169 UmkHmv8n9EDgtwnwEBZ6hx4VmqHKKeASEFQycD3G2TLrD6z6HGJym3bQAj8JTa3KK3PxB7mFdzWt8QMJtYUTSMRw1iXfKLN5X 55
Wallet password:
No payment id is included with this transaction. Is this okay?  (Y/Yes/N/No): y

Thread 1 "aeon-wallet-cli" received signal SIGSEGV, Segmentation fault.
tools::wallet2::create_transactions_2 (this=0x5555559876a0, dsts=std::vector of length 1, capacity 1 = {...}, ring_size=<optimized out>,
    unlock_time=<optimized out>, priority=<optimized out>, extra=std::vector of length 0, capacity 0, subaddr_account=0,
    subaddr_indices=std::set with 1 elements = {...}, trusted_daemon=true) at /home/x/aeonMaster2202019/src/wallet/wallet2.cpp:8041
8041          if (!use_rct && !dsts.empty() && tx.dsts.back().amount > ::config::BASE_REWARD_CLAMP_THRESHOLD)
(gdb) bt
#0  tools::wallet2::create_transactions_2 (this=0x5555559876a0, dsts=std::vector of length 1, capacity 1 = {...}, ring_size=<optimized out>,
    unlock_time=<optimized out>, priority=<optimized out>, extra=std::vector of length 0, capacity 0, subaddr_account=0,
    subaddr_indices=std::set with 1 elements = {...}, trusted_daemon=true) at /home/x/aeonMaster2202019/src/wallet/wallet2.cpp:8041
#1  0x0000555555620a7c in cryptonote::simple_wallet::transfer_main (this=0x7fffffffdf70, transfer_type=<optimized out>, args_=...)
    at /home/x/aeonMaster2202019/src/simplewallet/simplewallet.cpp:4690
#2  0x0000555555622a61 in cryptonote::simple_wallet::transfer_new (this=<optimized out>, args_=...)
    at /home/x/aeonMaster2202019/src/simplewallet/simplewallet.cpp:4890
#3  0x00005555556273da in boost::_mfi::mf1<bool, cryptonote::simple_wallet, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&>::operator() (a1=..., p=<optimized out>,
    this=<optimized out>) at /usr/local/include/boost/bind/mem_fn_template.hpp:165
#4  boost::_bi::list2<boost::_bi::value<cryptonote::simple_wallet*>, boost::arg<1> >::operator()<bool, boost::_mfi::mf1<bool, cryptonote::simple_wallet, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&>, boost::_bi::rrlist1<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&> > (a=<synthetic pointer>, f=..., this=<optimized out>)
    at /usr/local/include/boost/bind/bind.hpp:309
#5  boost::_bi::bind_t<bool, boost::_mfi::mf1<bool, cryptonote::simple_wallet, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&>, boost::_bi::list2<boost::_bi::value<cryptonote::simple_wallet*>, boost::arg<1> > >::operator()<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&> (a1=..., this=<optimized out>) at /usr/local/include/boost/bind/bind.hpp:1306
#6  boost::detail::function::function_obj_invoker1<boost::_bi::bind_t<bool, boost::_mfi::mf1<bool, cryptonote::simple_wallet, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&>, boost::_bi::list2<boost::_bi::value<cryptonote::simple_wallet*>, boost::arg<1> > >, bool, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&>::invoke (function_obj_ptr=..., a0=...)
    at /usr/local/include/boost/function/function_template.hpp:138
#7  0x000055555566e86f in boost::function1<bool, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&>::operator() (a0=std::vector of length 3, capacity 3 = {...}, this=0x55555597c660)
    at /usr/local/include/boost/function/function_template.hpp:769
#8  epee::command_handler::process_command_vec (cmd=std::vector of length 4, capacity 4 = {...}, this=<optimized out>)
    at /home/x/aeonMaster2202019/contrib/epee/include/console_handler.h:522
#9  epee::command_handler::process_command_str (this=<optimized out>, cmd=...) at /home/x/aeonMaster2202019/contrib/epee/include/console_handler.h:529
#10 0x0000555555655406 in boost::_mfi::mf1<bool, epee::command_handler, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>::call<epee::console_handlers_binder*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> (
    b1="transfer 169 UmkHmv8n9EDgtwnwEBZ6hx4VmqHKKeASEFQycD3G2TLrD6z6HGJym3bQAj8JTa3KK3PxB7mFdzWt8QMJtYUTSMRw1iXfKLN5X 55", u=@0x7fffffffd810: 0x7fffffffe130,
    this=0x7fffffffd800) at /usr/local/include/boost/bind/mem_fn_template.hpp:156
#11 boost::_mfi::mf1<bool, epee::command_handler, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>::operator()<epee::console_handlers_binder*> (a1=..., u=@0x7fffffffd810: 0x7fffffffe130, this=<optimized out>) at /usr/local/include/boost/bind/mem_fn_template.hpp:171
#12 boost::_bi::list2<boost::_bi::value<epee::console_handlers_binder*>, boost::arg<1> >::operator()<bool, boost::_mfi::mf1<bool, epee::command_handler, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::rrlist1<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> > (a=<synthetic pointer>, f=..., this=0x7fffffffd810) at /usr/local/include/boost/bind/bind.hpp:309
#13 boost::_bi::bind_t<bool, boost::_mfi::mf1<bool, epee::command_handler, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list2<boost::_bi::value<epee::console_handlers_binder*>, boost::arg<1> > >::operator()<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> (a1="transfer 169 UmkHmv8n9EDgtwnwEBZ6hx4VmqHKKeASEFQycD3G2TLrD6z6HGJym3bQAj8JTa3KK3PxB7mFdzWt8QMJtYUTSMRw1iXfKLN5X 55", this=<optimized out>)
    at /usr/local/include/boost/bind/bind.hpp:1306
#14 bool epee::async_console_handler::run<boost::_bi::bind_t<bool, boost::_mfi::mf1<bool, epee::command_handler, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list2<boost::_bi::value<epee::console_handlers_binder*>, boost::arg<1> > > >(boost::_bi::bind_t<bool, boost::_mfi::mf1<bool, epee::command_handler, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list2<boost::_bi::value<epee::conso---Type <return> to continue, or q <return> to quit---
le_handlers_binder*>, boost::arg<1> > >, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#1}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (
    cmd="transfer 169 UmkHmv8n9EDgtwnwEBZ6hx4VmqHKKeASEFQycD3G2TLrD6z6HGJym3bQAj8JTa3KK3PxB7mFdzWt8QMJtYUTSMRw1iXfKLN5X 55", __closure=0x7fffffffd7d0)
    at /home/x/aeonMaster2202019/contrib/epee/include/console_handler.h:305
#15 epee::async_console_handler::run<bool epee::async_console_handler::run<boost::_bi::bind_t<bool, boost::_mfi::mf1<bool, epee::command_handler, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list2<boost::_bi::value<epee::console_handlers_binder*>, boost::arg<1> > > >(boost::_bi::bind_t<bool, boost::_mfi::mf1<bool, epee::command_handler, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list2<boost::_bi::value<epee::console_handlers_binder*>, boost::arg<1> > >, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#1}>(std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool epee::async_console_handler::run<boost::_bi::bind_t<bool, boost::_mfi::mf1<bool, epee::command_handler, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list2<boost::_bi::value<epee::console_handlers_binder*>, boost::arg<1> > > >(boost::_bi::bind_t<bool, boost::_mfi::mf1<bool, epee::command_handler, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list2<boost::_bi::value<epee::console_handlers_binder*>, boost::arg<1> > >, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#1} const&, std::function<void ()>) (this=0x7fffffffe168, prompt=...,
    usage="", cmd_handler=..., exit_handler=...) at /home/x/aeonMaster2202019/contrib/epee/include/console_handler.h:369
#16 0x000055555560a4b4 in epee::async_console_handler::run<boost::_bi::bind_t<bool, boost::_mfi::mf1<bool, epee::command_handler, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list2<boost::_bi::value<epee::console_handlers_binder*>, boost::arg<1> > > >(boost::_bi::bind_t<bool, boost::_mfi::mf1<bool, epee::command_handler, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::_bi::list2<boost::_bi::value<epee::console_handlers_binder*>, boost::arg<1> > >, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>) (
    exit_handler=<error reading variable: access outside bounds of object referenced via synthetic pointer>, usage="",
    prompt=<error reading variable: access outside bounds of object referenced via synthetic pointer>, ch_handler=..., this=0x7fffffffe168)
    at /home/x/aeonMaster2202019/contrib/epee/include/console_handler.h:305
#17 epee::console_handlers_binder::run_handling(std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>) (
    exit_handler=<error reading variable: access outside bounds of object referenced via synthetic pointer>, usage_string="",
    prompt=<error reading variable: access outside bounds of object referenced via synthetic pointer>, this=0x7fffffffe130)
    at /home/x/aeonMaster2202019/contrib/epee/include/console_handler.h:563
#18 cryptonote::simple_wallet::run (this=0x7fffffffdf70) at /home/x/aeonMaster2202019/src/simplewallet/simplewallet.cpp:6660
#19 0x000055555561dacf in main (argc=2, argv=0x7fffffffe518) at /home/x/aeonMaster2202019/src/simplewallet/simplewallet.cpp:7773
```
```
(gdb) li
8036
8037        if (try_tx) {
8038          cryptonote::transaction test_tx;
8039          pending_tx test_ptx;
8040
8041          if (!use_rct && !dsts.empty() && tx.dsts.back().amount > ::config::BASE_REWARD_CLAMP_THRESHOLD)
8042          {
8043            // when the payment gets split, ensure that the partially paid amount doesn't have excessively small denominations
8044            const uint64_t subtracted_amount = tx.dsts.back().amount % ::config::BASE_REWARD_CLAMP_THRESHOLD;
8045            tx.dsts.back().amount -= subtracted_amount;
```

I understand very few will ever use a ringsize this large. The wallet should still not segfault.

**Comment by stoffu** [comment]
#102

**Comment by BigslimVdub** [comment]
great find cam. Who would have thought using an insanely high ring size would cause issues.
